version: "3"
services:
  cavo:
    image: index.docker.io/diogenss9999/vivit_adm:latest
    ports:
      - "1337:1337"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 2000
