version: '3'

services:
  api:
    environment:
      NODE_OPTIONS: --max-old-space-size=500
      DATABASE_CLIENT: postgres
      DATABASE_NAME: vivit
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: docker
    container_name: boilerplate_api
    build: .
    ports:
      - "1337:1337"
    depends_on:
      - db
    restart: on-failure

  db:
    container_name: boilerplate_db
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: vivit
